[workspace]
members = [
    "aegis-cli",
    "aegis-common",
    "aegis-ebpf",
    "aegis-tc",
    "xtask",
    "verification",
]
default-members = ["aegis-cli", "xtask"]
resolver = "2"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
