[package]
name = "aegis-ebpf"
version = "1.0.0"
edition = "2021"
license = "MIT"
description = "Aegis eBPF XDP ingress firewall program"

[dependencies]
aya-ebpf = "0.1.1"
aegis-common = { path = "../aegis-common", default-features = false }

[[bin]]
name = "aegis"
path = "src/main.rs"
